services:
  compute_node_1:
    image: "firstbatch/dkn-compute-node:latest"
    environment:
      RUST_LOG: "${RUST_LOG:-none,dkn_compute=info}"
      # Ganti dengan private key EVM kamu (format 0x...)
      DKN_WALLET_SECRET_KEY: "${DKN_WALLET_SECRET_KEY:-0xYOUR_PRIVATE_KEY_HERE}"
      # Nama model Ollama-style yang juga ada di MODEL_MAP proxy
      DKN_MODELS: "${DKN_MODELS:-llama3.3:70b-instruct-q4_K_M}"
      # Arahkan ke proxy, bukan ke server Ollama
      OLLAMA_HOST: "http://host.docker.internal"
      OLLAMA_PORT: "14441"
      OLLAMA_AUTO_PULL: "false"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - dria-nodes
    restart: "on-failure"

networks:
  dria-nodes:
    external: true